# -*- coding: utf-8 -*-
"""
Generate fine-tune JSONL from PDFs (export chunks as instruction/output or plain text).
Usage: python pdf_to_finetune_data.py [--output finetune_data/train.jsonl]
"""
import argparse
import json
from pathlib import Path

import config
from ingest import get_documents, split_documents

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=str(config.FINETUNE_DATA_DIR / "train.jsonl"), help="Output JSONL path")
    parser.add_argument("--format", choices=["instruction", "text"], default="instruction",
                        help="instruction = instruction/output Q&A format; text = plain text")
    args = parser.parse_args()
    config.ensure_dirs()
    docs = get_documents()
    if not docs:
        return
    chunks = split_documents(docs, chunk_size=512, chunk_overlap=32)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for i, c in enumerate(chunks):
            text = c.page_content.strip()
            if not text or len(text) < 20:
                continue
            if args.format == "instruction":
                # use chunk as output; instruction can be a generic prompt or later generated by model
                obj = {"instruction": "Summarize or answer briefly based on the document.", "output": text[:1024]}
            else:
                obj = {"text": text[:1024]}
            f.write(json.dumps(obj, ensure_ascii=False) + "\n")
    print(f"Wrote {out_path} with {len(chunks)} chunks. Tune with: python finetune.py --data {args.output}")

if __name__ == "__main__":
    main()
